
---
- name: Let's copy our executable script to remote location, execute script and get result back.
  remote_user: root
  #sudo: yes
  hosts: ubuntu
  tasks:
     #- name: Transfer executable script script
     #  copy: src=/opt/ashah/crunchify-script.sh dest=/opt/ashah mode=0777
 
     - name: Execute update
       command: apt update

     - name: Execute upgrade
       command: apt upgrade -y
